require('dotenv').config();
const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/auth');
const providerRoutes = require('./routes/providers');
const searchRoutes = require('./routes/search');
const bookingRoutes = require('./routes/bookings');
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({ status: 'ok' }));
app.use('/auth', authRoutes);
app.use('/provider', providerRoutes);
app.use('/search', searchRoutes);
app.use('/booking', bookingRoutes);
app.use((err, req, res, next) => {
  console.error(err);
  res.status(500).json({ error: 'server_error', message: err.message });
});
const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log(`API running on ${PORT}`));
